language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: B8Uv/uoDvjLYOssDxKpNW3zccFBTzyVnIRE+ZiZ0wZJz1tfyQwapfQVZmlZSbhK1uny7zOHdOYMwxCcQDKycWU5EictQVRpmgCVB2RCuMTW4kyNc8+Pr4I1KYrFNzF8DlKATBJjMnPXj9OITnPWKhFiy0by1kxits8unp4Svp2Q=
  on:
    tags: true
    branches: true
